ezyang/htmlpurifier

library/HTMLPurifier/Config.php
Adding PHPDoc @return statement for code completion in IDE
=> Missing @return

library/HTMLPurifier/DefinitionCache/Serializer.php
=> FIX directory not closing

library/HTMLPurifier/Encoder.php, tests/HTMLPurifier/EncoderTest.php
=> Fix surrogate pair range

library/HTMLPurifier/Lexer/DOMLex.php
Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>
=> Deal with old libxml incompatibilities.

extras/HTMLPurifierExtras.autoload-legacy.php, extras/HTMLPurifierExtras.autoload.php, library/HTMLPurifier.autoload-legacy.php, library/HTMLPurifier.autoload.php
=> Quarantine __autoload defs for PHP 7.2 compat

.travis.yml, NEWS
Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>
=> Changelog prep for release.

library/HTMLPurifier/AttrDef/URI/Host.php, library/HTMLPurifier/Lexer/DOMLex.php
Fixes #168.
Solution based on https://git.ispconfig.org/ispconfig/ispconfig3/commit/0e3cf6f51b4fd.
=> Use IDNA constants only if defined

INSTALL, INSTALL.fr.utf8
=> Update PHP version in INSTALL

.travis.yml, composer.json, library/HTMLPurifier/Language/messages/en-x-test.php, library/HTMLPurifier/Language/messages/en-x-testmini.php
I am currently reviewing our dependencies for PHP 7.3 compatibility.
This should run the the tests on 7.3 :)
=> Adds PHP 7.3 to Travis

library/HTMLPurifier/Config.php
=> Fixed error (PHP Notice: Undefined index: class in file Config.php on line 893)

library/HTMLPurifier/CSSDefinition.php, tests/HTMLPurifier/AttrDef/CSSTest.php
CSS: added "initial" and "inherit" to min-width + min-height, removed "auto"
CSS: added "initial" and "inherit" and "none" to max-width + max-height, removed "auto"
=> CSS: added "initial" and "inherit" to width + height

library/HTMLPurifier/ChildDef/Custom.php, library/HTMLPurifier/Encoder.php, library/HTMLPurifier/TagTransform/Font.php
=> Replace curly braces with square brackets in string offsets

library/HTMLPurifier/AttrDef/CSS/Number.php, tests/HTMLPurifier/AttrDef/CSS/AlphaValueTest.php, tests/HTMLPurifier/AttrDef/CSS/BackgroundTest.php, tests/HTMLPurifier/AttrDef/CSS/ColorTest.php, tests/HTMLPurifier/AttrDef/CSS/NumberTest.php, tests/HTMLPurifier/AttrDef/CSSTest.php
After this change, it trims leading zeros, but leaves the last zero if it is the only number.
=> Issue 238 remove leading zeroes except if there is only zero

library/HTMLPurifier.autoload-legacy.php, library/HTMLPurifier.autoload.php
update commit 
fix INI directive 'zend.ze1_compatibility_mode' is removed since PHP 5.3
=> Issue-256: Fix PHP 7.3 compatibility issues update zend.ze1_compatibility_mode mode

library/HTMLPurifier/ChildDef/Table.php, tests/HTMLPurifier/ChildDef/TableTest.php
…if there are no `<tbody>` or `<tr>` elements
=> Fixed Issue #264: <thead> element removed from <table>

library/HTMLPurifier/HTMLModule/Tidy/XHTMLAndHTML4.php
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col#attr-width
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table#attr-width
=> feat: transform deprecated width attribute

.github/workflows/ci.yml, composer.json
=> ci: test on php 8.0

composer.json
I have opened two PRs.
This one that extends work that I have done to solve #316 
and #318, that solves #316 directly.
=> Composer suggestions with extensions

library/HTMLPurifier/AttrDef/HTML/ContentEditable.php, library/HTMLPurifier/AttrTypes.php, tests/HTMLPurifier/AttrDef/HTML/ContentEditableTest.php
See https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable
=> Add contenteditable attribute definition

CHANGELOG.md, release.config.js
Reverts ezyang/htmlpurifier#339
=> Revert "fix: semantic release"

library/HTMLPurifier/URIScheme/tel.php, tests/HTMLPurifier/AttrDef/URITest.php, tests/HTMLPurifier/URIFilter/MakeAbsoluteTest.php, tests/HTMLPurifier/URIParserTest.php, tests/HTMLPurifier/URISchemeTest.php
See https://stackoverflow.com/a/42923505
Closes #352
=> fix: Add support for encoded tel URI schemes.

library/HTMLPurifier/CSSDefinition.php, tests/HTMLPurifier/AttrDef/CSSTest.php
* Updated CSS definition and added support for all `text-decoration` related properties 
* Updated CSS test for the added properties
* Updated CSS definition file and changed arrays into short syntax
=> feat: Add support for all text-decoration properties

composer.json
Signed-off-by: Edward Z. Yang <ezyang@meta.com>
=> fix: fix CI

library/HTMLPurifier/DefinitionCache/Serializer.php
Fixes https://github.com/ezyang/htmlpurifier/issues/371
Signed-off-by: Edward Z. Yang <ezyang@meta.com>
=> fix: Don't suggest chmod to 777

library/HTMLPurifier/ChildDef/Table.php
See [Issue 398](https://github.com/ezyang/htmlpurifier/issues/398)
=> fix: checking that node has property name

library/HTMLPurifier/AttrDef/CSS/Ratio.php, library/HTMLPurifier/CSSDefinition.php, tests/HTMLPurifier/AttrDef/CSS/RatioTest.php, tests/HTMLPurifier/AttrDef/CSSTest.php
Adds support for the CSS ratio value type and the aspect-ratio property.
Reference: 
https://www.w3.org/TR/css-values-4/#ratio-value
https://www.w3.org/TR/css-sizing-4/#ratios
=> feat: Add support for CSS aspect-ratio
