ezyang/htmlpurifier

tests/common.php
While setting up testing it took me a while to find where the simpletest library has to be wrt the configuration variable because I was getting no error on the failing require in common.
This PR simply adds a message and exception to make this case more explicit.
HTH
=> feat(Tests) inform if SimpleTest library cannot be found

library/HTMLPurifier/Bootstrap.php
While profiling a part of coreBOS I saw that getPath() function was called 67 times for a total of 5.50
I had a look at the function and saw that it could benefit from a local cache array, so I added that and the the time fell significantly.
I ran the tests and all past correctly.
=> speed(Bootstrap) static cache to getPath to decrease time to response

library/HTMLPurifier/DefinitionCache/Serializer.php, tests/HTMLPurifier/DefinitionCache/SerializerTest.php
The previous chmod behaviour was unclear and didn't agree with the documentation, and was causing a few unwanted side effects.
i.e., http://htmlpurifier.org/live/configdoc/plain.html#Cache.SerializerPermissions
First I removed the bitwise & that was happening when custom permissions were applied to the file. The & was making it impossible to actually set the permissions that were set in the config. E.g., if the permissions were set to 0777 then the actual value would come out as 1000 or something.
I also removed a block of code from the _prepareDir method that was erroneously throwing an error when the custom chmod value in the configuration was set to null.
I updated the unit test to be a) more easy to read and understand, and b) just test the permission of the file, since the …
=> changed chmod behaviour in Serializer

library/HTMLPurifier/Strategy/MakeWellFormed.php
Fixes #108.
Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>
=> Remove $a = array($a) which is miscompiled by Zend OpCache.

library/HTMLPurifier/DefinitionCache/Serializer.php
Sometimes Serializer from another thread already creaded dir - this commit resolves this issue.
=> Fix E_WARNING when cache directory exists

library/HTMLPurifier/AttrDef/URI/Host.php, tests/HTMLPurifier/AttrDef/URI/HostTest.php
idn_to_ascii($string) shows deprecation notice in PHP 7.2 , see
https://wiki.php.net/rfc/deprecate-and-remove-intl_idna_variant_2003
and even in earlier PHP versions it is incorrect in some cases, for example it converts "faß.de" into "fass.de"
see http://www.unicode.org/reports/tr46/
=> Use IDNA2008 for converting domains to ASCII

library/HTMLPurifier/Lexer/PH5P.php, maintenance/PH5P.php
Hi, I'm a developer to TikiWiki and we use your htmlpurifier. Following our philosophy, I fixed some typos we found upstream, i.e., in your code. 
Thanks!
=> Small typos in comments

library/HTMLPurifier/Length.php, tests/HTMLPurifier/AttrDef/CSSTest.php
I have seen the request in #147 and think that the reporter's request makes sense, so I had a go. From what I could grasp adding them to `HTMLPurifier_Length::$allowedUnits` should be sufficient, as it is used by `HTMLPurifier_AttrDef_CSS_Length` and the validators make use of that particular array. The tests that I added seem to support this.
I chose to add the units as displayed at https://www.w3schools.com/cssref/css_units.asp. I was also considering adding `%` as a unit, but then realised that it must have been covered elsewhere, perhaps in `HTMLPurifier_AttrDef_CSS_Percentage`.
Are there any general reasons against adding support for CSS 3? Relative units are just one step towards that, but I think they will be useful as they are increasingly used in documents.
=> Add relative length units for CSS 3 support

library/HTMLPurifier/Injector.php
This is an error starting in PHP 7.2, causing a test failure:
> Unexpected PHP Error [count(): Parameter must be an array or an object that implements Countable] severity [2] in [HtmlPurifier/library/HTMLPurifier/Injector.php line 160]
> 	in testErrorRequiredElementNotAllowed
> 	in HTMLPurifier_Strategy_MakeWellFormed_InjectorTest
I used `empty` to parallel an existing test in the same method.
=> PHP 7.2: Skip counting currentNesting if null in Injector

README.md
Normally people should not use the latest master but the latest stable release instead.
=> Suggest stable Composer installation

benchmarks/.htaccess, maintenance/.htaccess
```
Deny from all
```
is depricated by [apache 2.4](https://httpd.apache.org/docs/2.4/upgrading.html).
The new directive is:
```
Require all denied
```
I changed the files to support <2.4 and >2.4 as suggested in https://github.com/nextcloud/news/issues/340
There is a mod for backward [compatibility](https://httpd.apache.org/docs/2.4/mod/mod_access_compat.html) but I think it's better to support both.
=> .htaccess support apache 2.4+

configdoc/usage.xml, library/HTMLPurifier/HTMLModule/SafeScripting.php, tests/HTMLPurifier/HTMLModule/SafeScriptingTest.php
Hi,
the end `</script>` tag is mandatory (https://www.w3.org/TR/html4/interact/scripts.html)
and in my chrome `<script src="....js" />` does not work (the script JS does not load), that is why this PR.
=> [SafeScripting] disable autoclosing of <script /> tag

.travis.yml
PHP 5.4 and 5.5 builds on Travis CI are currently failing with the following error:
```
$ phpenv global 5.4 2>/dev/null
5.4 is not pre-installed; installing
Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/php/binaries/ubuntu/16.04/x86_64/php-5.4.tar.bz2
0.12s$ curl -s -o archive.tar.bz2 $archive_url && tar xjf archive.tar.bz2 --directory /
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
0.00s0.02s$ phpenv global 5.4
rbenv: version `5.4' not installed
The command "phpenv global 5.4" failed and exited with 1 during .
Your build has been stopped.
```
=> Fix PHP 5.4 and 5.5 builds on Travis CI

library/HTMLPurifier/Lexer/DOMLex.php
Hi @ezyang,
I'd like to ask what's the current policy on supporting prehistoric PHP versions? The minimum PHP version in [`composer.json`](https://github.com/ezyang/htmlpurifier/blob/master/composer.json#L16) is set at 5.2, which is the reason I submit this PR.
The DOM Lexer (default lexer implementation) in version 4.11.0 does not work on PHP 5.3 because of [this line](https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier/Lexer/DOMLex.php#L77).
Loading HTML document in PHP 5.3 fails with:
```
Fatal error: Call to a member function getElementsByTagName() on a non-object
```
After disabling (for the investigation purposes) `muteErrorHandler` we see the culprit:
```
Warning: DOMDocument::loadHTML() expects exactly 1 parameter, 2 given
```
According to the …
=> Fix DOM Lexer for PHP versions older than 5.4

library/HTMLPurifier/AttrDef/HTML/Bool.php, library/HTMLPurifier/HTMLModule.php
This PR fixes a few errors in phpdoc params:
- `$attr_includes` param in `HTMLModule::addElement()` can be a string, and this is how it's mostly used in the codebase (e.g. [here](https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier/HTMLModule/Text.php#L35)).
- The `$contents` param in `HTMLModule::addElement()` can be an instance of `HTMLPurifier_ChildDef` (as noted [here](https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier/HTMLModule.php#L161)), and this should also be reflected in phpdoc.
Additionally there is a minor fix to phpdoc of `AttrDef_HTML_Bool`, as the name of a boolean attribute is a `string`, not a `bool` (example usage [here](https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier/HTMLModule/Forms.php#L76)).
=> Fix phpdoc params in HTMLModule::addElement() and Bool attr

composer.json
These classes are autoloaded by a custom autoloader. The classes don't follow PSR-0 and as such will trigger a warning when dumping an optimized autoloader in composer 1.10+
=> Exclude language classes from autoloader optimization

library/HTMLPurifier/Config.php
getDefinition can return null, this wasn't properly hinted leaning to false error detections with static analyzers
=> Correct typehinting of maybeGet*

library/HTMLPurifier/Printer/HTMLDefinition.php
Passing parameters to implode() in reverse order is deprecated, use
implode($glue, $parts) instead of implode($parts, $glue).
Part of https://tracker.moodle.org/browse/MDL-67115
(those seem to be the only 2 occurrences in code)
=> Correct implode() params for php74 compliance

library/HTMLPurifier/HTMLModule/Tidy/XHTMLAndHTML4.php
I've been using xemlock/htmlpurifier-html5 and realised that it's removing the `bgcolor` attribute from `<tr>` elements. I tried to add `"HTML.TidyAdd" => ["tr@bgcolor"],` but it didn't do anything.
I think this is a long standing bug, given the comment says `@bgcolor for tr` but there's never been any commit that added / removed it?
With this addition `"HTML.TidyAdd" => ["tr@bgcolor"],` now works and so does `"HTML.TidyLevel" => "heavy"`
=> Added tr@bgcolor to tidy

NEWS
Corresponding PRs (#230, #242) are about PHP 7.4 and PHP 6.4 has never existed 🙂.
=> Fix typo in the 4.13.0 NEWS: PHP 6.4 never existed

library/HTMLPurifier/Config.php
This function has been DEPRECATED as of PHP 7.4.0. Relying on this function is highly discouraged. It is basically useless as of PHP 5.4 because it will always return false, so for modern applications it can be safely removed. But as this library still supports PHP 5.2 — according to the constraints in composer.json — I added a version check to prevent this method from being called (and trigger a notice) on PHP >=7.4. Fixes #272.
See: https://www.php.net/manual/en/function.get-magic-quotes-gpc.php
=> Check PHP version before checking magic quotes

library/HTMLPurifier/Injector/Linkify.php
[`preg_split()`](https://www.php.net/manual/en/function.preg-split.php) returns `string[]|false`
In PHP 7.2 `count()` generates a warning if the given argument is not countable:
> Warning: count(): Parameter must be an array or an object that implements Countable
https://3v4l.org/daRFo
Unfortunately I cannot add a test as I'm not sure what data causes the issue. That being said, the issue seems fairly obvious based on the return type of `preg_split`.
=> Fix "Parameter must be an array or an object that implements Countable"

library/HTMLPurifier/AttrDef/CSS/Background.php, library/HTMLPurifier/CSSDefinition.php, tests/HTMLPurifier/AttrDef/CSSTest.php
I've added support for CSS3 tag background-size according to https://www.w3schools.com/cssref/css3_pr_background-size.asp
=> CSS: Add "background-size" tag support

.github/workflows/ci.yml
I asked GitHub why actions were not running on PRs, and their response was:
> This happened because the pull request was from a fork. The workflow file was configured to run only when triggered on push from the master branch.
This partially reverts https://github.com/ezyang/htmlpurifier/pull/297 due to the test suite not being compatible with PHP 8.
=> Fix GH workflow conditions

library/HTMLPurifier/HTMLModule/Tidy.php
Proposed code is PHP5 and PHP7 compatible. PHP5 interpreted `$e->$type[$attr]` as `$e->{$type[$attr]}`, but the expected behavior based on workaround is consistent with PHP7 interpretation: `($e->$type)[$attr]`. By using curly braces `{$e->$type}[$attr]` there is a forced interpretation order working for both versions.
Details can be found on https://www.php.net/manual/en/migration70.incompatible.php (section "Changes to the handling of indirect variables, properties, and methods")
=> Remove unnecessary reference assigment

.github/workflows/ci.yml, extras/FSTools.php, library/HTMLPurifier/ElementDef.php, library/HTMLPurifier/Length.php, library/HTMLPurifier/Lexer.php, library/HTMLPurifier/Lexer/PH5P.php, library/HTMLPurifier/PropertyListIterator.php, library/HTMLPurifier/StringHash.php, library/HTMLPurifier/URIFilter/Munge.php
Most of these were caught by the tests. The last commit fixed an issue the tests didn't catch that just came up using the library.
=> PHP 8.1: fix various deprecations/errors in newest version of PHP

library/HTMLPurifier/AttrTransform/NameSync.php, library/HTMLPurifier/ChildDef/List.php, library/HTMLPurifier/Injector/RemoveSpansWithoutAttributes.php, library/HTMLPurifier/Lexer.php, tests/HTMLPurifier/AttrTransform/NameSyncTest.php, tests/HTMLPurifier/AttrValidator_ErrorsTest.php, tests/HTMLPurifier/URIFilterHarness.php
PHP 8.2 deprecates the creation of dynamic properties on objects: https://wiki.php.net/rfc/deprecate_dynamic_properties. This pull request fixes some of the low-hanging fruit of properties that are dynamically created.
I've opted to use the `public` access modifier, as this most closely matches the previous behavior: Dynamically created properties are visible from everywhere. The only non-trivial – and possibly breaking – change is happening in `RemoveSpansWithoutAttributes` as that one does not add a dynamic property to itself, but to another object instead.
This pull request does not fix all deprecations, a follow up change will be required to fix the remainder.
=> Fix some PHP 8.2 deprecations

library/HTMLPurifier/URIFilter/HostBlacklist.php, tests/HTMLPurifier/URIFilter/HostBlacklistTest.php
`$uri->host` can be `null`:
```
object(HTMLPurifier_URI)#14528 (7) {
["scheme"]=>
NULL
["userinfo"]=>
NULL
["host"]=>
NULL
["port"]=>
NULL
["path"]=>
string(0) ""
["query"]=>
NULL
["fragment"]=>
string(3) "foo"
}
```
Closes #322
=> Fix #322 - PHP 8.1 deprecation notice in HostBlacklist URIFilter

library/HTMLPurifier/Encoder.php
This is the very simplest replacement of utf8_encode/_decode with their mbstring counterparts: it doesn't attempt to use mbstring more fully in the absence of iconv for encodings beyond ISO 8859-1 or anything like that, nor does it report mbstring's absence in any specific way if we fall down there and it's missing (this could be added of course).
The idea here is just to indicate that a simple replacement does work fine and passes the tests.
See #320, #324
=> Replace 8.1-deprecated utf8_ funcs with mbstring

.github/workflows/ci.yml
This does not introduce any functional difference and is intended as a
future-proofing change.
see https://github.com/actions/checkout/releases/tag/v3.0.0
=> Update to `actions/checkout@v3`

tests/test_files.php
Selecting the `fstools` tests also executed the `htmlt` tests.
=> Fix test selection logic in tests/test_files.php

library/HTMLPurifier/AttrTransform/SafeParam.php, tests/HTMLPurifier/DefinitionCache/DecoratorHarness.php, tests/HTMLPurifier/EntityParserTest.php
Read the description in #319 for more details.
-------------------------
At this point fixing more issues gets painful, because some of the errors are in simpletest and not obvious to fix to me. Unfortunately simpletest's own tests already fail even with PHP 7.4 making it even harder to make the necessary changes.
It might make sense to migrate HTMLPurifier's tests to another maintained testing framework (e.g. PHPUnit) to future proof it for upcoming PHP versions (I specifically can imagine PHP 9 being painful once it appears). Unfortunately I don't have the time resources that are necessary to make this happen.
=> Fix some more PHP 8.2 deprecations

tests/HTMLPurifier/DefinitionTestable.php
Not really sure that this is the best way to handle it, but it does the trick :shrug: 
```
All HTML Purifier tests on PHP 8.2.0RC1
Exception 1!
Unexpected PHP Error [Creation of dynamic property HTMLPurifier_DefinitionTestable::$info_random is deprecated] severity [8192] in [/v/tests/HTMLPurifier/DefinitionCache/SerializerTest.php line 41]
in test
in HTMLPurifier_DefinitionCache_SerializerTest
Exception 2!
Unexpected PHP Error [Creation of dynamic property HTMLPurifier_DefinitionTestable::$info_random is deprecated] severity [8192] in [/v/library/HTMLPurifier/DefinitionCache/Serializer.php line 73]
in test
in HTMLPurifier_DefinitionCache_SerializerTest
Exception 3!
Unexpected PHP Error [Creation of dynamic property HTMLPurifier_DefinitionTestable::$info_random is deprecated] severity …
```
=> Fix creation of dynamic property notices on PHP 8.2

tests/HTMLPurifier/Strategy/MakeWellFormed/EndRewindInjector.php
```
All HTML Purifier tests on PHP 8.2.0RC1
Exception 1!
Unexpected PHP Error [Creation of dynamic property HTMLPurifier_Token_Start::$_InjectorTest_EndRewindInjector_delete is deprecated] severity [8192] in [/v/tests/HTMLPurifier/Strategy/MakeWellFormed/EndRewindInjector.php line 26]
in testFunction
in HTMLPurifier_Strategy_MakeWellFormed_EndRewindInjectorTest
Exception 2!
Unexpected PHP Error [Creation of dynamic property HTMLPurifier_Token_Start::$_InjectorTest_EndRewindInjector_delete is deprecated] severity [8192] in [/v/tests/HTMLPurifier/Strategy/MakeWellFormed/EndRewindInjector.php line 26]
in testPadded
in HTMLPurifier_Strategy_MakeWellFormed_EndRewindInjectorTest
Exception 3!
Unexpected PHP Error [Creation of dynamic property …
```
=> Fix creation of dynamic property

library/HTMLPurifier/HTMLModule/CommonAttributes.php, tests/HTMLPurifier/Strategy/ValidateAttributesTest.php
I forgot to add the attribute to a collection in https://github.com/ezyang/htmlpurifier/pull/332 so the attribute was never actually being validated.
=> Fix contenteditable attribute definition

CHANGELOG.md, release.config.js
I noticed that https://github.com/ezyang/htmlpurifier/commit/523407fb06eb9e5f3d59889b3978d5bfe94299c8 didn't update all the files:
```
'VERSION',
'NEWS',
'Doxyfile',
'library/HTMLPurifier.php',
'library/HTMLPurifier/Config.php',
'library/HTMLPurifier.includes.php'
```
I believe this PR fixes that. Here's an example I ran locally - the important bit being `Update /v/NEWS` and `Found 6 file(s) to commit`:
```bash
$ npx semantic-release --no-ci
[6:41:28 PM] [semantic-release] › ℹ  Running semantic-release version 19.0.5
[6:41:28 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[6:41:28 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/exec"
[6:41:28 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" …
```
=> fix: semantic release

library/HTMLPurifier/Printer/ConfigForm.php
Fixes:
```
103  Access to an undefined property HTMLPurifier_Printer_ConfigForm::$genConfig 
197  Access to an undefined property HTMLPurifier_Printer_ConfigForm::$genConfig
```
=> fix: Fixed undefined property

library/HTMLPurifier/AttrDef/URI/Host.php
Making phpstan happy, it complains about a non-existing class:
`Instantiated class Net_IDNA2 not found.`
=> fix: Added class_exists('Net_IDNA2') around optional external class

library/HTMLPurifier/Lexer/DOMLex.php
Fixes:
`114  Method HTMLPurifier_Lexer_DOMLex::tokenizeDOM() should return HTMLPurifier_Token but return statement is missing.`
=> fix: Fixed wrong return PHPDoc

library/HTMLPurifier/HTMLModule/Tidy.php
Fixes:
`222  Method HTMLPurifier_HTMLModule_Tidy::makeFixes() should return array but return statement is missing.`
=> fix: Fixed missing return value

library/HTMLPurifier/Filter/ExtractStyleBlocks.php, tests/HTMLPurifier/Filter/ExtractStyleBlocksTest.php
Fix for issue https://github.com/ezyang/htmlpurifier/issues/357
Added a check if `$decls` is an array before the `foreach` and not keeping the value if it's not.
Also added a unit test for that case.
=> fix: CSSTidy ImportantComments not handled properly

library/HTMLPurifier/AttrTransform/TargetBlank.php
When `Attr.TargetBlank` is enabled, a PHP warning is logged if an `href` attribute contains an invalid URI scheme.
Normally an `href` like `javascript:void(0)` or `itms-apps://itunes.apple.com/developer/id1234567890` would be removed by the default `HTMLPurifier_Config` configuration.
However, it's possible to insert a URL with an unknown context from a trusted source after filtering. For instance, an `HTMLPurifier_URIFilter` extension.
This patch doesn't change any functionality or permit anything new, it simply adds error checking around `$url->getSchemeObj()` which returns `HTMLPurifier_URIScheme|false`.
The `false` case is currently not handled, resulting in error log entries under PHP 8.x like the following:
~~~
Attempt to read property "browsable" on bool …
=> fix: Invalid scheme check in Attr.TargetBlank

library/HTMLPurifier/DefinitionCacheFactory.php, library/HTMLPurifier/LanguageFactory.php, library/HTMLPurifier/Lexer.php
This PR removes the usage of the secondary argument in `class_exists()` checks in HTML Purifier. This secondary argument is being used to disable autoloading the class if it has not yet been autoloaded.
The current implementation breaks composer based projects where a class may not have been included or required yet via composers autoloader, but has been registered as a definition cache:
```php
$cache = \App\Purifier\RemoteFilesystemDefinition::class;
HTMLPurifier_DefinitionCacheFactory::instance()->register($cache, $cache);
$htmlConfig = HTMLPurifier_Config::create($config);
$htmlConfig->set('Cache.DefinitionImpl', $cache);
```
Upon usage:
```
ErrorException : Unrecognized DefinitionCache App\Purifier\RemoteFilesystemDefinition, using Serializer instead
```
This exception can be resolved …
=> fix: Remove unnecessary disablement of autoload in `class_exists` usage

library/HTMLPurifier/UnitConverter.php, tests/HTMLPurifier/UnitConverterTest.php
When using somtehing like `setlocale(LC_ALL, 'de_DE');` the function `sprintf('%.1f, ...)'` will use a comma for decimal separation. The function `is_numeric()` will output `false` for strings containing a comma. Thereby I had to replace the decimal separator of the used locale with a dot.
=> fix: Support for locales using decimal separators other than . (dot)

library/HTMLPurifier/URIScheme/tel.php
=> feat: Allows commas to be included in tel URI

library/HTMLPurifier/Lexer.php, tests/HTMLPurifier/LexerTest.php
Remove special handling of IE conditional comments
=> fix: Ignore conditional comments

library/HTMLPurifier/AttrDef/URI/Host.php, tests/HTMLPurifier/AttrDef/URI/HostTest.php
Hello,
Thank you so much for developing and maintaining HTML Purifier.
I have created a pull request for #405.
Recently, we have seen cases where we want to consider URIs that contain "_", such as "_dmarc.example.com".
I think this PR adjusts Core.AllowHostnameUnderscore to consider that "_" is defined as Unreserved Characters in RFC 3986. 
Thank you.
=> fix: Adjust Core.AllowHostnameUnderscore to consider that "_" is defined as Unreserved Characters in RFC 3986

library/HTMLPurifier/AttrDef/CSS.php, library/HTMLPurifier/CSSDefinition.php, library/HTMLPurifier/Filter/ExtractStyleBlocks.php, tests/HTMLPurifier/AttrDef/CSSTest.php, tests/HTMLPurifier/Filter/ExtractStyleBlocksTest.php
Support for the universal or "CSS-wide" property values (`initial`, `inherit`, and `unset`, see https://www.w3.org/TR/css-values/#common-keywords) is mixed at the moment.
Several properties manually are defined to allow `initial` and `inherit`, currently:
- background-size
- width
- height
- max-width
- max-height
- min-width
- min-height
- text-decoration-line
- text-decoration-style
- text-decoration-thickness
Separately, `inherit` is allowed for _every_ property, but only in the `style` attribute, not in an extracted style block (the code that does this is only in the CSS AttrDef).
This PR removes the special case in AttrDef_CSS and the explicit enum definitions in the CSSDefinition, and replaces both with checks in AttrDef_CSS and Filter_ExtractStyleBlocks against an enum of …
=> feat: Allow universal CSS values for all properties

library/HTMLPurifier/HTMLModule/Iframe.php, tests/HTMLPurifier/HTMLT/safe-iframe-youtube-allowfullscreen.htmlt
(closes #409)
This PR adds support for the [allowfullscreen attribute for the iframe element](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-allowfullscreen). The attribute is only allowed when the HTML.Trusted configuration option is enabled.
=> feat: Add allowfullscreen attr for iframe

library/HTMLPurifier/Token/Tag.php, tests/HTMLPurifier/HTMLDefinitionTest.php
I have created a pull request for #393.
Issue #393 had shown a case where a deprecated error occurs using PHP 8.1 or later.
This PR avoids that error.
[Example]
Contents of "test-393.php"
```
<?php
require_once './htmlpurifier/library/HTMLPurifier.auto.php';
$config = HTMLPurifier_Config::createDefault();
$purifier = new HTMLPurifier($config);
$config->set('HTML.AllowedElements', ['a']);
$config->set('HTML.AllowedAttributes', ['href']);
$config->set('Core.LexerImpl', 'DirectLex');
$clean_html = $purifier->purify('<a href="https://example.com/" 10="hoge">Test</a>');
echo $clean_html . "\n";
```
```
% /opt/homebrew/opt/php@8.0/bin/php -v | head -n 1
PHP 8.0.30 (cli) (built: Jun  6 2024 19:16:32) ( NTS )
% /opt/homebrew/opt/php@8.0/bin/php test-393.php
<a href="https://example.com/">Test</a> …
```
=> fix: Avoid a deprecated error when the attribute name is numeric and DirectLex is used

library/HTMLPurifier/EntityParser.php
Hello :wave: 
The following code causes the warning “Undefined array key 2”
```php
$html = "/<style>{src:'<style/onload=this.onload=confirm(1)>'/</style>';";
$purifier = new \HTMLPurifier();
$purifier->purify($html);
```
This also solves the problem reported here https://github.com/ezyang/htmlpurifier/issues/413
=> fix: undefined array key warning
